[2025-06-06T00:36:08.266+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: events_ingestion.fetch_and_store_events_task scheduled__2025-06-06T00:00:00+00:00 [queued]>
[2025-06-06T00:36:08.328+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: events_ingestion.fetch_and_store_events_task scheduled__2025-06-06T00:00:00+00:00 [queued]>
[2025-06-06T00:36:08.334+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-06T00:36:08.424+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_events_task> on 2025-06-06 00:00:00+00:00
[2025-06-06T00:36:08.438+0000] {standard_task_runner.py:60} INFO - Started process 184 to run task
[2025-06-06T00:36:08.453+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'events_ingestion', 'fetch_and_store_events_task', 'scheduled__2025-06-06T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/api_to_db_dag_events.py', '--cfg-path', '/tmp/tmp_qsfr3le']
[2025-06-06T00:36:08.469+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask fetch_and_store_events_task
[2025-06-06T00:36:08.742+0000] {task_command.py:423} INFO - Running <TaskInstance: events_ingestion.fetch_and_store_events_task scheduled__2025-06-06T00:00:00+00:00 [running]> on host e2020a2f916b
[2025-06-06T00:36:09.281+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='events_ingestion' AIRFLOW_CTX_TASK_ID='fetch_and_store_events_task' AIRFLOW_CTX_EXECUTION_DATE='2025-06-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-06T00:00:00+00:00'
[2025-06-06T00:36:09.289+0000] {api_to_db_dag_events.py:39} INFO - Đang gọi API: https://app.circle.so/api/admin/v2/events?page=1&per_page=60
[2025-06-06T00:36:10.009+0000] {api_to_db_dag_events.py:42} INFO - Đã lấy 1 bản ghi từ API (nhiều trang).
[2025-06-06T00:36:10.011+0000] {api_to_db_dag_events.py:49} INFO - Đang kết nối đến cơ sở dữ liệu với Conn ID: QUANG
[2025-06-06T00:36:10.026+0000] {base.py:83} INFO - Using connection ID 'QUANG' for task execution.
[2025-06-06T00:36:10.263+0000] {api_to_db_dag_events.py:55} INFO - Kết nối cơ sở dữ liệu thành công.
[2025-06-06T00:36:10.325+0000] {api_to_db_dag_events.py:146} ERROR - Lỗi khi thao tác với database: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sql12783027`.`events`, CONSTRAINT `events_ibfk_1` FOREIGN KEY (`community_member_id`) REFERENCES `community_members` (`community_member_id`))')
[2025-06-06T00:36:10.326+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_to_db_dag_events.py", line 135, in fetch_and_store_events
    cur.executemany(insert_sql, values_to_insert)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 241, in executemany
    return self._do_execute_many(
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 275, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`sql12783027`.`events`, CONSTRAINT `events_ibfk_1` FOREIGN KEY (`community_member_id`) REFERENCES `community_members` (`community_member_id`))')
[2025-06-06T00:36:10.356+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=events_ingestion, task_id=fetch_and_store_events_task, execution_date=20250606T000000, start_date=20250606T003608, end_date=20250606T003610
[2025-06-06T00:36:10.392+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task fetch_and_store_events_task ((1452, 'Cannot add or update a child row: a foreign key constraint fails (`sql12783027`.`events`, CONSTRAINT `events_ibfk_1` FOREIGN KEY (`community_member_id`) REFERENCES `community_members` (`community_member_id`))'); 184)
[2025-06-06T00:36:10.406+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-06T00:36:10.441+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
